site_name: EUD Lab
repo_url: https://github.com/saebyeok0306/EUD-Lab
repo_name: EUD-Lab
copyright: Copyright &copy; 2025 saebyeok0306 All rights reserved.
edit_uri: edit/main/docs/

theme:
  name: material
  features:
    - content.action.edit
    - content.footnote.tooltips
    - content.code.copy
    - navigation.indexes
    - navigation.prune
    - navigation.tabs
    - navigation.top
#    - navigation.footer
    - navigation.tracking
  language: ko
  icon:
    edit: material/pencil 
    view: material/eye
    repo: fontawesome/brands/github
    previous: fontawesome/solid/angle-left
    next: fontawesome/solid/angle-right
  logo: assets/logo.png
  favicon: assets/favicon.png
  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: black
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to system preference
  font:
    text: Roboto
    code: JetBrains Mono
  custom_dir: overrides

plugins:
  - blog:
      enabled: true
      post_url_date_format: yyyy.MM.dd
      authors_profiles: true
      authors_file: blog/.authors.yml
      archive_name: Archive
  - search:
      separator: '[\s\u200b\-_,:!=\[\]()"`/]+|\.(?!\d)|&[lg]t;|(?!\b)(?=[A-Z][a-z])'
  - minify:
      minify_html: true
  - git-revision-date-localized:
      enabled: !ENV [CI, false]
      enable_creation_date: false
      type: date
      fallback_to_build_date: true
  - git-committers:
      enabled: !ENV [CI, false]
      repository: saebyeok0306/EUD-Lab
      branch: main
      token: !ENV ["CI_JOB_TOKEN"]
      cache_dir: .cache/git-committers
  - gen-files:
      scripts:
        - scripts/gen_nav_list.py
  - meta:
      meta_file: .meta.yml

extra:
  status:
    new: Recently added
    deprecated: Deprecated
  analytics:
    provider: google
    property: !ENV GOOGLE_ANALYTICS_KEY
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/saebyeok0306
    - icon: fontawesome/solid/mug-saucer
      link: https://cafe.naver.com/edac

extra_javascript:
  - javascripts/address_list.js
  - javascripts/cunit_list.js
  - javascripts/extra.js

extra_css:
  - stylesheets/extra.css

markdown_extensions:
  - tables
  - admonition
  - footnotes
  - pymdownx.highlight:
      pygments_lang_class: true
      anchor_linenums: true
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

hooks:
  - scripts/hooks.py